### ISSUE TITLE
Simplify jauntiness CSS

### ISSUE THREAD

**Issue by excitedleigh** [pyconau/2020-website#7]
https://github.com/pyconau/2020-website/blob/e505e71ef02554f8c2717408aedafdb50e905ed1/frontend/index.scss#L76

Idle thought: rather than doing this (including the bunch of trigonometry that got me to that value, which isn't in the codebase but I'm sure is on a sheet of paper somewhere :S), could we not set the `transform-origin` to `0 $logo-width`, causing it to rotate around the logo regardless of browser width (which was the original aim here)?

**Comment by daisylb** [comment]
Done as part of pyconline stuff.
